import { type ComponentRef, forwardRef } from "react";
import type { GridProps } from "./types";
import { tv } from "tailwind-variants";

const gridVariants = tv({
  base: "grid",
  variants: {
    cols: {
      1: "grid-cols-1",
      2: "grid-cols-2",
      3: "grid-cols-3",
      4: "grid-cols-4",
      5: "grid-cols-5",
      6: "grid-cols-6",
      7: "grid-cols-7",
      8: "grid-cols-8",
      9: "grid-cols-9",
      10: "grid-cols-10",
      11: "grid-cols-11",
      12: "grid-cols-12",
    },
    smCols: {
      1: "sm:grid-cols-1",
      2: "sm:grid-cols-2",
      3: "sm:grid-cols-3",
      4: "sm:grid-cols-4",
      5: "sm:grid-cols-5",
      6: "sm:grid-cols-6",
      7: "sm:grid-cols-7",
      8: "sm:grid-cols-8",
      9: "sm:grid-cols-9",
      10: "sm:grid-cols-10",
      11: "sm:grid-cols-11",
      12: "sm:grid-cols-12",
    },
    mdCols: {
      1: "md:grid-cols-1",
      2: "md:grid-cols-2",
      3: "md:grid-cols-3",
      4: "md:grid-cols-4",
      5: "md:grid-cols-5",
      6: "md:grid-cols-6",
      7: "md:grid-cols-7",
      8: "md:grid-cols-8",
      9: "md:grid-cols-9",
      10: "md:grid-cols-10",
      11: "md:grid-cols-11",
      12: "md:grid-cols-12",
    },
    lgCols: {
      1: "lg:grid-cols-1",
      2: "lg:grid-cols-2",
      3: "lg:grid-cols-3",
      4: "lg:grid-cols-4",
      5: "lg:grid-cols-5",
      6: "lg:grid-cols-6",
      7: "lg:grid-cols-7",
      8: "lg:grid-cols-8",
      9: "lg:grid-cols-9",
      10: "lg:grid-cols-10",
      11: "lg:grid-cols-11",
      12: "lg:grid-cols-12",
    },
    xlCols: {
      1: "xl:grid-cols-1",
      2: "xl:grid-cols-2",
      3: "xl:grid-cols-3",
      4: "xl:grid-cols-4",
      5: "xl:grid-cols-5",
      6: "xl:grid-cols-6",
      7: "xl:grid-cols-7",
      8: "xl:grid-cols-8",
      9: "xl:grid-cols-9",
      10: "xl:grid-cols-10",
      11: "xl:grid-cols-11",
      12: "xl:grid-cols-12",
    },
    "2xlCols": {
      1: "2xl:grid-cols-1",
      2: "2xl:grid-cols-2",
      3: "2xl:grid-cols-3",
      4: "2xl:grid-cols-4",
      5: "2xl:grid-cols-5",
      6: "2xl:grid-cols-6",
      7: "2xl:grid-cols-7",
      8: "2xl:grid-cols-8",
      9: "2xl:grid-cols-9",
      10: "2xl:grid-cols-10",
      11: "2xl:grid-cols-11",
      12: "2xl:grid-cols-12",
    },
    gap: {
      0: "gap-0",
      1: "gap-1",
      2: "gap-2",
      3: "gap-3",
      4: "gap-4",
      5: "gap-5",
      6: "gap-6",
      8: "gap-8",
      10: "gap-10",
      12: "gap-12",
      16: "gap-16",
    },
    gapX: {
      0: "gap-x-0",
      1: "gap-x-1",
      2: "gap-x-2",
      3: "gap-x-3",
      4: "gap-x-4",
      5: "gap-x-5",
      6: "gap-x-6",
      8: "gap-x-8",
      10: "gap-x-10",
      12: "gap-x-12",
      16: "gap-x-16",
    },
    gapY: {
      0: "gap-y-0",
      1: "gap-y-1",
      2: "gap-y-2",
      3: "gap-y-3",
      4: "gap-y-4",
      5: "gap-y-5",
      6: "gap-y-6",
      8: "gap-y-8",
      10: "gap-y-10",
      12: "gap-y-12",
      16: "gap-y-16",
    },
    smGap: {
      0: "sm:gap-0",
      1: "sm:gap-1",
      2: "sm:gap-2",
      3: "sm:gap-3",
      4: "sm:gap-4",
      5: "sm:gap-5",
      6: "sm:gap-6",
      8: "sm:gap-8",
      10: "sm:gap-10",
      12: "sm:gap-12",
      16: "sm:gap-16",
    },
    mdGap: {
      0: "md:gap-0",
      1: "md:gap-1",
      2: "md:gap-2",
      3: "md:gap-3",
      4: "md:gap-4",
      5: "md:gap-5",
      6: "md:gap-6",
      8: "md:gap-8",
      10: "md:gap-10",
      12: "md:gap-12",
      16: "md:gap-16",
    },
    lgGap: {
      0: "lg:gap-0",
      1: "lg:gap-1",
      2: "lg:gap-2",
      3: "lg:gap-3",
      4: "lg:gap-4",
      5: "lg:gap-5",
      6: "lg:gap-6",
      8: "lg:gap-8",
      10: "lg:gap-10",
      12: "lg:gap-12",
      16: "lg:gap-16",
    },
    xlGap: {
      0: "xl:gap-0",
      1: "xl:gap-1",
      2: "xl:gap-2",
      3: "xl:gap-3",
      4: "xl:gap-4",
      5: "xl:gap-5",
      6: "xl:gap-6",
      8: "xl:gap-8",
      10: "xl:gap-10",
      12: "xl:gap-12",
      16: "xl:gap-16",
    },
    "2xlGap": {
      0: "2xl:gap-0",
      1: "2xl:gap-1",
      2: "2xl:gap-2",
      3: "2xl:gap-3",
      4: "2xl:gap-4",
      5: "2xl:gap-5",
      6: "2xl:gap-6",
      8: "2xl:gap-8",
      10: "2xl:gap-10",
      12: "2xl:gap-12",
      16: "2xl:gap-16",
    },
    smGapX: {
      0: "sm:gap-x-0",
      1: "sm:gap-x-1",
      2: "sm:gap-x-2",
      3: "sm:gap-x-3",
      4: "sm:gap-x-4",
      5: "sm:gap-x-5",
      6: "sm:gap-x-6",
      8: "sm:gap-x-8",
      10: "sm:gap-x-10",
      12: "sm:gap-x-12",
      16: "sm:gap-x-16",
    },
    mdGapX: {
      0: "md:gap-x-0",
      1: "md:gap-x-1",
      2: "md:gap-x-2",
      3: "md:gap-x-3",
      4: "md:gap-x-4",
      5: "md:gap-x-5",
      6: "md:gap-x-6",
      8: "md:gap-x-8",
      10: "md:gap-x-10",
      12: "md:gap-x-12",
      16: "md:gap-x-16",
    },
    lgGapX: {
      0: "lg:gap-x-0",
      1: "lg:gap-x-1",
      2: "lg:gap-x-2",
      3: "lg:gap-x-3",
      4: "lg:gap-x-4",
      5: "lg:gap-x-5",
      6: "lg:gap-x-6",
      8: "lg:gap-x-8",
      10: "lg:gap-x-10",
      12: "lg:gap-x-12",
      16: "lg:gap-x-16",
    },
    xlGapX: {
      0: "xl:gap-x-0",
      1: "xl:gap-x-1",
      2: "xl:gap-x-2",
      3: "xl:gap-x-3",
      4: "xl:gap-x-4",
      5: "xl:gap-x-5",
      6: "xl:gap-x-6",
      8: "xl:gap-x-8",
      10: "xl:gap-x-10",
      12: "xl:gap-x-12",
      16: "xl:gap-x-16",
    },
    "2xlGapX": {
      0: "2xl:gap-x-0",
      1: "2xl:gap-x-1",
      2: "2xl:gap-x-2",
      3: "2xl:gap-x-3",
      4: "2xl:gap-x-4",
      5: "2xl:gap-x-5",
      6: "2xl:gap-x-6",
      8: "2xl:gap-x-8",
      10: "2xl:gap-x-10",
      12: "2xl:gap-x-12",
      16: "2xl:gap-x-16",
    },
    smGapY: {
      0: "sm:gap-y-0",
      1: "sm:gap-y-1",
      2: "sm:gap-y-2",
      3: "sm:gap-y-3",
      4: "sm:gap-y-4",
      5: "sm:gap-y-5",
      6: "sm:gap-y-6",
      8: "sm:gap-y-8",
      10: "sm:gap-y-10",
      12: "sm:gap-y-12",
      16: "sm:gap-y-16",
    },
    mdGapY: {
      0: "md:gap-y-0",
      1: "md:gap-y-1",
      2: "md:gap-y-2",
      3: "md:gap-y-3",
      4: "md:gap-y-4",
      5: "md:gap-y-5",
      6: "md:gap-y-6",
      8: "md:gap-y-8",
      10: "md:gap-y-10",
      12: "md:gap-y-12",
      16: "md:gap-y-16",
    },
    lgGapY: {
      0: "lg:gap-y-0",
      1: "lg:gap-y-1",
      2: "lg:gap-y-2",
      3: "lg:gap-y-3",
      4: "lg:gap-y-4",
      5: "lg:gap-y-5",
      6: "lg:gap-y-6",
      8: "lg:gap-y-8",
      10: "lg:gap-y-10",
      12: "lg:gap-y-12",
      16: "lg:gap-y-16",
    },
    xlGapY: {
      0: "xl:gap-y-0",
      1: "xl:gap-y-1",
      2: "xl:gap-y-2",
      3: "xl:gap-y-3",
      4: "xl:gap-y-4",
      5: "xl:gap-y-5",
      6: "xl:gap-y-6",
      8: "xl:gap-y-8",
      10: "xl:gap-y-10",
      12: "xl:gap-y-12",
      16: "xl:gap-y-16",
    },
    "2xlGapY": {
      0: "2xl:gap-y-0",
      1: "2xl:gap-y-1",
      2: "2xl:gap-y-2",
      3: "2xl:gap-y-3",
      4: "2xl:gap-y-4",
      5: "2xl:gap-y-5",
      6: "2xl:gap-y-6",
      8: "2xl:gap-y-8",
      10: "2xl:gap-y-10",
      12: "2xl:gap-y-12",
      16: "2xl:gap-y-16",
    },
  },
  defaultVariants: {
    cols: 12,
    gap: 4,
  },
});

export { gridVariants };

export const Grid = forwardRef<ComponentRef<"div">, GridProps>(function (
  {
    as,
    cols,
    gap,
    gapX,
    gapY,
    sm,
    md,
    lg,
    xl,
    "2xl": xl2,
    className,
    children,
    ...props
  },
  ref
) {
  const Component = as || "div";

  return (
    <Component
      className={gridVariants({
        cols,
        gap,
        gapX,
        gapY,
        smCols: sm?.cols,
        mdCols: md?.cols,
        lgCols: lg?.cols,
        xlCols: xl?.cols,
        "2xlCols": xl2?.cols,
        smGap: sm?.gap,
        mdGap: md?.gap,
        lgGap: lg?.gap,
        xlGap: xl?.gap,
        "2xlGap": xl2?.gap,
        smGapX: sm?.gapX,
        mdGapX: md?.gapX,
        lgGapX: lg?.gapX,
        xlGapX: xl?.gapX,
        "2xlGapX": xl2?.gapX,
        smGapY: sm?.gapY,
        mdGapY: md?.gapY,
        lgGapY: lg?.gapY,
        xlGapY: xl?.gapY,
        "2xlGapY": xl2?.gapY,
        className,
      })}
      ref={ref}
      {...props}
    >
      {children}
    </Component>
  );
});
